p8105_hw2_zj2358
================
Zhezheng Jin
2023-10-02

## Problem 1

data clean of pols_month

``` r
pols_month = read_csv(file = "pols-month.csv") %>%
  janitor::clean_names() %>%
  separate(mon, into = c("year", "month", "day"), sep = "-") %>%
  mutate(month = month.name[as.integer(month)],
         president = ifelse(prez_dem == 1, "dem", ifelse(prez_gop == 1, "gop", NA))) %>%
  select(-prez_dem, -prez_gop, -day)

pols_month
```

    ## # A tibble: 822 × 9
    ##    year  month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <chr> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1 1947  January        23      51     253      23      45     198 dem      
    ##  2 1947  February       23      51     253      23      45     198 dem      
    ##  3 1947  March          23      51     253      23      45     198 dem      
    ##  4 1947  April          23      51     253      23      45     198 dem      
    ##  5 1947  May            23      51     253      23      45     198 dem      
    ##  6 1947  June           23      51     253      23      45     198 dem      
    ##  7 1947  July           23      51     253      23      45     198 dem      
    ##  8 1947  August         23      51     253      23      45     198 dem      
    ##  9 1947  September      23      51     253      23      45     198 dem      
    ## 10 1947  October        23      51     253      23      45     198 dem      
    ## # ℹ 812 more rows

data clean of snp

``` r
snp = read_csv(file = "snp.csv") %>%
  janitor::clean_names() %>%
  separate(date, into = c("month", "day", "year"), sep = "/") %>%
  mutate(year = ifelse(year >= 0 & year <= 15, paste("20", year, sep = ""), paste("19", year, sep = ""))) %>%
  mutate(month = month.name[as.integer(month)]) %>%
  arrange(year, month) %>%
  select(year, month, day, everything()) %>%
  select(-day)

snp
```

    ## # A tibble: 787 × 3
    ##    year  month    close
    ##    <chr> <chr>    <dbl>
    ##  1 1950  April     18.0
    ##  2 1950  August    18.4
    ##  3 1950  December  20.4
    ##  4 1950  February  17.2
    ##  5 1950  January   17.0
    ##  6 1950  July      17.8
    ##  7 1950  June      17.7
    ##  8 1950  March     17.3
    ##  9 1950  May       18.8
    ## 10 1950  November  19.5
    ## # ℹ 777 more rows

tidy data unemployment

``` r
unemployment = read_csv(file = "unemployment.csv") %>%
  pivot_longer(cols = -Year, names_to = "month", values_to = "unemployment") %>%
  mutate(month = tolower(month)) %>%
  mutate(month = case_when(
    month %in% c("jan") ~ "January",
    month %in% c("feb") ~ "February",
    month %in% c("mar") ~ "March",
    month %in% c("apr") ~ "April",
    month %in% c("may") ~ "May",
    month %in% c("jun") ~ "June",
    month %in% c("jul") ~ "July",
    month %in% c("aug") ~ "August",
    month %in% c("sep") ~ "September",
    month %in% c("oct") ~ "October",
    month %in% c("nov") ~ "November",
    month %in% c("dec") ~ "December",
    TRUE ~ NA_character_
  )) %>%
  select(year=Year, month, unemployment, everything())

unemployment
```

    ## # A tibble: 816 × 3
    ##     year month     unemployment
    ##    <dbl> <chr>            <dbl>
    ##  1  1948 January            3.4
    ##  2  1948 February           3.8
    ##  3  1948 March              4  
    ##  4  1948 April              3.9
    ##  5  1948 May                3.5
    ##  6  1948 June               3.6
    ##  7  1948 July               3.6
    ##  8  1948 August             3.9
    ##  9  1948 September          3.8
    ## 10  1948 October            3.7
    ## # ℹ 806 more rows

merge datasets

``` r
merged_data <- left_join(pols_month, snp, by = c("year", "month"))
unemployment$year <- as.character(unemployment$year)
final_data <- left_join(merged_data, unemployment, by = c("year", "month"))

final_data
```

    ## # A tibble: 822 × 11
    ##    year  month   gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##    <chr> <chr>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ##  1 1947  January      23      51     253      23      45     198 dem          NA
    ##  2 1947  Februa…      23      51     253      23      45     198 dem          NA
    ##  3 1947  March        23      51     253      23      45     198 dem          NA
    ##  4 1947  April        23      51     253      23      45     198 dem          NA
    ##  5 1947  May          23      51     253      23      45     198 dem          NA
    ##  6 1947  June         23      51     253      23      45     198 dem          NA
    ##  7 1947  July         23      51     253      23      45     198 dem          NA
    ##  8 1947  August       23      51     253      23      45     198 dem          NA
    ##  9 1947  Septem…      23      51     253      23      45     198 dem          NA
    ## 10 1947  October      23      51     253      23      45     198 dem          NA
    ## # ℹ 812 more rows
    ## # ℹ 1 more variable: unemployment <dbl>

The dataset `final_data` comprises three primary sources of data, each
contributing unique insights. Firstly, `pols_month` offers political
data, containing information about the monthly representation of both
Republican and Democratic officials at the levels of governor, senator,
and representative. Secondly, `snp` contributes financial data,
providing monthly closing values for the S&P stock index, which is often
used as a benchmark for stock market performance. Lastly, `unemployment`
presents economic data in a wide format, featuring monthly unemployment
rates. The merged `final_data` dataset seamlessly combines these
sources, resulting in a comprehensive dataset with 822 rows and 11
columns. The dataset spans from 1947, 2015, encompassing a wide range of
historical information. Key variables in the dataset include year,
month, gov_gop, sen_gop, rep_gop, gov_dem, sen_dem, rep_dem, president,
close, unemployment.

## Problem 2

Read and Clean: MTW

``` r
mtw_df = read_excel(
  "202309 Trash Wheel Collection Data.xlsx",
  cell_cols("A:N"),
  sheet = "Mr. Trash Wheel") %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(homes_powered_N = weight_tons*500/30,
         wheel_type = c("MT")) %>% 
  relocate(wheel_type,dumpster,year,month) 
mtw_df
```

    ## # A tibble: 584 × 16
    ##    wheel_type dumpster year  month date                weight_tons
    ##    <chr>         <dbl> <chr> <chr> <dttm>                    <dbl>
    ##  1 MT                1 2014  May   2014-05-16 00:00:00        4.31
    ##  2 MT                2 2014  May   2014-05-16 00:00:00        2.74
    ##  3 MT                3 2014  May   2014-05-16 00:00:00        3.45
    ##  4 MT                4 2014  May   2014-05-17 00:00:00        3.1 
    ##  5 MT                5 2014  May   2014-05-17 00:00:00        4.06
    ##  6 MT                6 2014  May   2014-05-20 00:00:00        2.71
    ##  7 MT                7 2014  May   2014-05-21 00:00:00        1.91
    ##  8 MT                8 2014  May   2014-05-28 00:00:00        3.7 
    ##  9 MT                9 2014  June  2014-06-05 00:00:00        2.52
    ## 10 MT               10 2014  June  2014-06-11 00:00:00        3.76
    ## # ℹ 574 more rows
    ## # ℹ 10 more variables: volume_cubic_yards <dbl>, plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   plastic_bags <dbl>, wrappers <dbl>, sports_balls <dbl>,
    ## #   homes_powered <dbl>, homes_powered_N <dbl>

Read and Clean: PTW

``` r
ptw_df = read_excel(
  "202309 Trash Wheel Collection Data.xlsx",
  cell_cols("A:M"),
  sheet = "Professor Trash Wheel") %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(homes_powered_N = weight_tons*500/30,
         wheel_type = c("PT")) %>% 
  relocate(wheel_type,dumpster,year,month) 
ptw_df
```

    ## # A tibble: 106 × 15
    ##    wheel_type dumpster  year month    date                weight_tons
    ##    <chr>         <dbl> <dbl> <chr>    <dttm>                    <dbl>
    ##  1 PT                1  2017 January  2017-01-02 00:00:00        1.79
    ##  2 PT                2  2017 January  2017-01-30 00:00:00        1.58
    ##  3 PT                3  2017 February 2017-02-26 00:00:00        2.32
    ##  4 PT                4  2017 February 2017-02-26 00:00:00        3.72
    ##  5 PT                5  2017 February 2017-02-28 00:00:00        1.45
    ##  6 PT                6  2017 March    2017-03-30 00:00:00        1.71
    ##  7 PT                7  2017 April    2017-04-01 00:00:00        1.82
    ##  8 PT                8  2017 April    2017-04-20 00:00:00        2.37
    ##  9 PT                9  2017 May      2017-05-10 00:00:00        2.64
    ## 10 PT               10  2017 May      2017-05-26 00:00:00        2.78
    ## # ℹ 96 more rows
    ## # ℹ 9 more variables: volume_cubic_yards <dbl>, plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   plastic_bags <dbl>, wrappers <dbl>, homes_powered <dbl>,
    ## #   homes_powered_N <dbl>

Read and Clean: GTW

``` r
gtw_df = read_excel(
  "202309 Trash Wheel Collection Data.xlsx",
  cell_cols("A:L"),
  sheet = "Gwynnda Trash Wheel") %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(homes_powered_N = weight_tons*500/30,
         wheel_type = c("GT")) %>% 
  relocate(wheel_type,dumpster,year,month) 
gtw_df
```

    ## # A tibble: 155 × 14
    ##    wheel_type dumpster  year month  date                weight_tons
    ##    <chr>         <dbl> <dbl> <chr>  <dttm>                    <dbl>
    ##  1 GT                1  2021 July   2021-07-03 00:00:00        0.93
    ##  2 GT                2  2021 July   2021-07-07 00:00:00        2.26
    ##  3 GT                3  2021 July   2021-07-07 00:00:00        1.62
    ##  4 GT                4  2021 July   2021-07-16 00:00:00        1.76
    ##  5 GT                5  2021 July   2021-07-30 00:00:00        1.53
    ##  6 GT                6  2021 August 2021-08-11 00:00:00        2.06
    ##  7 GT                7  2021 August 2021-08-14 00:00:00        1.9 
    ##  8 GT                8  2021 August 2021-08-16 00:00:00        2.16
    ##  9 GT                9  2021 August 2021-08-16 00:00:00        2.6 
    ## 10 GT               10  2021 August 2021-08-17 00:00:00        3.21
    ## # ℹ 145 more rows
    ## # ℹ 8 more variables: volume_cubic_yards <dbl>, plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>, homes_powered_N <dbl>

Combine them together

``` r
mtw_df$year <- as.double(mtw_df$year)
combined_df <- bind_rows(mtw_df, ptw_df, gtw_df)
combined_df
```

    ## # A tibble: 845 × 16
    ##    wheel_type dumpster  year month date                weight_tons
    ##    <chr>         <dbl> <dbl> <chr> <dttm>                    <dbl>
    ##  1 MT                1  2014 May   2014-05-16 00:00:00        4.31
    ##  2 MT                2  2014 May   2014-05-16 00:00:00        2.74
    ##  3 MT                3  2014 May   2014-05-16 00:00:00        3.45
    ##  4 MT                4  2014 May   2014-05-17 00:00:00        3.1 
    ##  5 MT                5  2014 May   2014-05-17 00:00:00        4.06
    ##  6 MT                6  2014 May   2014-05-20 00:00:00        2.71
    ##  7 MT                7  2014 May   2014-05-21 00:00:00        1.91
    ##  8 MT                8  2014 May   2014-05-28 00:00:00        3.7 
    ##  9 MT                9  2014 June  2014-06-05 00:00:00        2.52
    ## 10 MT               10  2014 June  2014-06-11 00:00:00        3.76
    ## # ℹ 835 more rows
    ## # ℹ 10 more variables: volume_cubic_yards <dbl>, plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   plastic_bags <dbl>, wrappers <dbl>, sports_balls <dbl>,
    ## #   homes_powered <dbl>, homes_powered_N <dbl>

The dataset `combined_df` comprises data from three trash-collecting
entities: Mr. Trash Wheel, Professor Trash Wheel, and Gwynnda Trash
Wheel. In total, there are 845 observations in the combined dataset,
representing various trash collection events. Key variables include
trash_weight, which denotes the weight of trash collected during each
event, and homes_powered, representing the approximate number of homes
powered by the collected trash. The total weight of trash collected by
Professor Trash Wheel is 216.26 tons, and the total number of cigarette
butts collected by Gwynnda in July 2021 is 16300.

## Problem 3

Import, clean, and tidy MCI_bsaeline

``` r
baseline = read_csv(file = "MCI_baseline.csv", skip=1) %>%
  janitor::clean_names() %>%
  mutate(sex = factor(sex, labels = c("Female", "Male")),
         apoe4 = factor(apoe4, labels = c("APOE4 non-carrier", "APOE4 carrier")),
         age_at_onset = as.numeric(age_at_onset)) %>%
  drop_na(age_at_onset)
baseline
```

    ## # A tibble: 97 × 6
    ##       id current_age sex    education apoe4             age_at_onset
    ##    <dbl>       <dbl> <fct>      <dbl> <fct>                    <dbl>
    ##  1     3        62.5 Male          16 APOE4 carrier             66.8
    ##  2     5        66   Male          16 APOE4 non-carrier         68.7
    ##  3     7        66.5 Male          18 APOE4 non-carrier         74  
    ##  4    13        63.1 Male          12 APOE4 carrier             69  
    ##  5    14        58.4 Female        20 APOE4 non-carrier         66.2
    ##  6    18        67.8 Male          16 APOE4 non-carrier         69.8
    ##  7    22        67.3 Female        20 APOE4 carrier             74.6
    ##  8    26        64.8 Female        20 APOE4 carrier             71.1
    ##  9    30        66.3 Female        12 APOE4 non-carrier         73.1
    ## 10    39        68.3 Female        16 APOE4 carrier             70.2
    ## # ℹ 87 more rows

The import process involves skipping the first line when reading the CSV
file, cleaning column names with `janitor` function, encoding
categorical variables using `mutate`, converting data types where
necessary, and handling missing data to prepare the dataset for further
analysis. There are 97 participants were recruited in the dataset, and
of these, 97 developed MCI. The average baseline age is 66 years old.
There are 65.22% of women in the study are APOE4 carriers.

Import, clean, and tidy mci_amyloid

``` r
amyloid <- read_csv("mci_amyloid.csv", skip=1) %>%
  janitor::clean_names() %>%
  pivot_longer(baseline:time_8,
               names_prefix="time_",
               names_to="years_since_diagnosed",
               values_to="apoe4") %>%
  mutate(years_since_diagnosed=replace(years_since_diagnosed, years_since_diagnosed=="baseline", 0)) %>%
  mutate(years_since_diagnosed=as.numeric(years_since_diagnosed)) 
  
amyloid
```

    ## # A tibble: 2,435 × 3
    ##    study_id years_since_diagnosed apoe4      
    ##       <dbl>                 <dbl> <chr>      
    ##  1        1                     0 0.1105487  
    ##  2        1                     2 <NA>       
    ##  3        1                     4 0.109325197
    ##  4        1                     6 0.104756131
    ##  5        1                     8 0.107257697
    ##  6        2                     0 0.107481183
    ##  7        2                     2 0.109157373
    ##  8        2                     4 0.109457839
    ##  9        2                     6 0.105729713
    ## 10        2                     8 0.10661845 
    ## # ℹ 2,425 more rows

The import process for the `amyloid` dataset consists of several key
steps. First, the CSV file is read using `read_csv`, and the header row
is skipped to ensure data accuracy. Next, the `janitor::clean_names()`
function is applied to standardize and clean the column names.
Categorical variables are encoded for analysis, and data types are
converted as needed. There are 487 participants were recruited in the
dataset, with 3 variables.

Identify participants unique to each dataset

``` r
participants_only_in_baseline <- baseline %>%
  anti_join(amyloid, by = c("id" = "study_id")) %>%
  select(id)

participants_only_in_amyloid <- amyloid %>%
  anti_join(baseline, by = c("study_id" = "id")) %>%
  select(study_id)
```

There are 3 Participants unique to the baseline dataset, and 1965
Participants unique to the amyloid dataset.

Combine datasets for participants present in both datasets

``` r
MCI_combined <- baseline %>%
  inner_join(amyloid, by = c("id" = "study_id"))
```

The resulting dataset `MCI_combined` retains participants who appear in
both the `baseline` and `amyloid` datasets, and has 94 participants and
8 variables. The variables include id, current_age, sex, education,
apoe4.x, age_at_onset, years_since_diagnosed, apoe4.y.

Export the combined dataset as a CSV

``` r
write.csv(MCI_combined, "MCI_combined.csv", row.names = FALSE)
```
